### ISSUE TITLE
Workbook.caller raises TypeError when called from an add-in (xlam)

### ISSUE THREAD

**Issue by jimm-domingo** [ZoomerAnalytics/xlwings#240]
Got this error on Windows with an Excel add-in that works fine on OS X:

```
Traceback (most recent call last):
  ...
  File "C:\Users\James\Documents\projects\[...snip...].py", line 95, in store_mesg
    toolkit_addin = Workbook.caller()
  File "c:\Users\James\Anaconda3\envs\my-env\lib\site-packages\xlwings\main.py", line 197, in caller
    xl_workbook = xlplatform.get_xl_workbook_from_xl(fullname, app_target=sys.argv[3])
TypeError: get_xl_workbook_from_xl() got an unexpected keyword argument 'app_target'
```

The signatures of the get_xl_workbook_from_xl function differ between the platforms:

In `_xlmac.py`:

    def get_xl_workbook_from_xl(fullname, app_target=None):

vs `_xlwindows.py`:

    def get_xl_workbook_from_xl(fullname):

*  Anaconda3 2.3.0
*  xlwings 0.3.6

**Comment by fzumstein** [comment]
Is it possible that the VBA module is not in the same version as the python package? Check at the top of the VBA module. Besides that, is there anything stopping you from upgrading to the latest version? v0.4.0 introduced an important update that resolves a lot of possible bugs when connecting to workbooks.

**Comment by jimm-domingo** [comment]
Thanks for the prompt response.  You were right about the version mismatch.  The VBA module is 0.4.0, and the conda environment on the OS X machine had xlwings 0.4.0 installed, but the environment on the Windows was still at xlwings 0.3.6.

However, after I upgraded that latter environment to 0.4.0, the caller() method raised a different error:

```
Traceback (most recent call last):
  ...
  File "C:\Users\James\Documents\projects\[...snip...].py", line 101, in store_mesg
    toolkit_addin = Workbook.caller()
  File "c:\Users\James\Anaconda3\envs\my-env\lib\site-packages\xlwings\main.py", line 196, in caller
    xl_app, xl_workbook = xlplatform.get_open_workbook(fullname, hwnd=sys.argv[4])
TypeError: 'NoneType' object is not iterable
```

It's still not happy when the caller is an add-in.

**Comment by fzumstein** [comment]
Not sure if I fully get your situation: Are you using `RunPython` from within an Excel-addin, i.e. not just a standard VBA module?

**Comment by jimm-domingo** [comment]
Calling `RunPython` from a standard VBA module in an Excel add-in (a `*.xlam` file).

**Comment by fzumstein** [comment]
Ah I see, as such this issue is already open (and might have some hints how to make things work for now): #153
